[supervisord]
nodaemon=true
user=root
environment=PYENV_ROOT="/opt/pyenv",PATH="/opt/pyenv/shims:/opt/pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

[program:websocket_backend]
command=python3 /usr/share/Redkit-Proxy/backend.py
autostart=true
autorestart=true
directory=/usr/share/Redkit-Proxy
stderr_logfile=/var/log/backend.err.log
stdout_logfile=/var/log/backend.out.log
environment=HOME="/home/redkit",USER="redkit",PYENV_ROOT="/opt/pyenv",PATH="/opt/pyenv/shims:/opt/pyenv/bin:/usr/local/bin:/usr/bin:/bin"

[program:mitm_proxy]
command=mitmdump -s /usr/share/Redkit-Proxy/backend.py -p 8080 --ssl-insecure
autostart=true
autorestart=true
directory=/usr/share/Redkit-Proxy
stderr_logfile=/var/log/proxy.err.log
stdout_logfile=/var/log/proxy.out.log
environment=HOME="/home/redkit",USER="redkit",PYENV_ROOT="/opt/pyenv",PATH="/opt/pyenv/shims:/opt/pyenv/bin:/usr/local/bin:/usr/bin:/bin"